### ISSUE TITLE
Initialize the project

### ISSUE THREAD

**Issue by AlbertoG22** [BrightCoders-Institute/reto-reservacion-de-vuelos-team2#1]
Inicialize the project of Flight Reservation in React Native.

```[tasklist]
### Tasks
- [x] Clone the repository in a local machine.
- [x] Run the comand `npx react-native@latest init NewApp`.
- [x] Move the previous content (files on the repo) inside the new folder created.
- [x] Execute the project using `npx react-native run-android` or `npx react-native run-ios` to verify that the project works correctly.
```
