### ISSUE TITLE
User authentication (Google)

### ISSUE THREAD

**Issue by AlbertoG22** [BrightCoders-Institute/reto-reservacion-de-vuelos-team2#10]
## REQUIREMENTS / DESCRIPTION

> Make the authentication for the app using the Google method using Firebase.

## Tasks

- [x] Enable the "Google" sign-in provider on the Firebase Console.
- [x] Implement the funtionality of authentication in the app with React Native logic.
- [x] Handling errors of the authentication (provide feedback to the user).
- [x] Redirect to Home Page when login successfully.
