### ISSUE TITLE
Connection with database

### ISSUE THREAD

**Issue by Alfredo20164920** [BrightCoders-Institute/reto-reservacion-de-vuelos-team2#2]
## REQUIREMENTS / DESCRIPTION

>Create database on firebase and create basic connection with a basic component
### Tasks
- [x] Understand basic concepts about firebase
- [x] Investigate how to authenticate users with firebase
- [x] Configure new database 
- [x] Create connection with the project
