### ISSUE TITLE
LogIn with Email/Password and Google

### ISSUE THREAD

**Issue by AlbertoG22** [BrightCoders-Institute/reto-reservacion-de-vuelos-team2#20]
## REQUIREMENTS / DESCRIPTION

> Make the LogIn process of Email/Password and Google.

## TASKS
- [x] Implement the funtionality of authentication in the app with React Native logic.
- [x] Handling errors of the authentication (provide feedback to the user).
- [x] Redirect to Home Page when login successfully.
- [x] Use of custom hooks to reduce code duplication.
- [x] Create/Implement a Loder Spinner component to show the process of LogIn and Sign Up.
