### ISSUE TITLE
User authentication (email, password)

### ISSUE THREAD

**Issue by AlbertoG22** [BrightCoders-Institute/reto-reservacion-de-vuelos-team2#9]
## REQUIREMENTS / DESCRIPTION

> Make the authentication for the app using the Email/Password method using Firebase.

## Tasks
- [x] Enable the "Email/Password" sign-in provider on the Firebase Console.
- [x] Implement the funtionality of authentication in the app with React Native logic.
- [x] Handling errors of the authentication (provide feedback to the user).
- [x] Redirect to Home Page when login successfully.
